[build]
  command = "./netlify-build.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    # No additional inputs to avoid potential configuration conflicts
