[build]
  command = "./netlify-build.sh"
  publish = ".next/standalone"
  functions = ".next/server"

# Plugin disabled due to persistent file not found errors
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Handle Next.js routing
[[redirects]]
  from = "/_next/static/*"
  to = "/_next/static/:splat"
  status = 200

[[redirects]]
  from = "/_next/data/*"
  to = "/_next/data/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
