[build]
  command = "./netlify-build.sh"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"
  # Skip image optimization which can cause build issues
  NEXT_DISABLE_IMAGE_OPTIMIZATION = "true"
