[build]
  command = "CI=false npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD -- ."

[build.environment]
  NETLIFY = "true"
  NODE_VERSION = "18"

# Disable automatic static HTML generation for 404/500 pages
[build.processing]
  skip_processing = true

# Use @netlify/plugin-nextjs without any extra processing
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    skipBuildLogs = "true"
    # Force serverless mode
    useServerlessFunctions = "true"
    # Skip static HTML generation
    generateStaticRoutes = "false"
